### ISSUE TITLE
memory_bram introduces $dff in VexRiscv

### ISSUE THREAD

**Issue by pepijndevos** [ZirconiumX/74xx-liberty#13]
When looking at the stat output for VexRiscv you can see two `$dff`, of the lowercase, pre-synth kind. It appears they originate from the `memory_bram` rule. Commenting that out gives a `$mem` item, and uncommenting `memory_map` gets rid of all the weirdness.

Probably the solution is to move the bram step to before `synth` so that the output registers it creates are synthesized. But maybe there is a reason it's all the way at the end?

**Comment by ZirconiumX** [comment]
Check the ordering of your commands; if you're leaking $dff cells, it
probably means you're trying to do this after techmap. Either move it to
before techmap, or run techmap again.

**Comment by pepijndevos** [comment]
I'm seeing this on origin/master, ruling out most of my own dumbfuckery, with the exception of badly messing up git.
It seems to originate from the bram pass. Might try moving that up tomorrow.
